name: Test Upload

on:
  push:
    branches: 
      - main

jobs:
  build_latex:
    runs-on: ubuntu-latest
    if: github.actor == 'i-v-a-n-h-o-e'
    steps:
      - uses: actions/checkout@v3
      - name: latex2pdf
        id: compile-latex-document
        uses: thomas-chauvet/latex2pdf-action@1.1.0
        with:
          output_dir: output
          main_latex_file: main.tex
      - uses: actions/upload-artifact@v4
        with:
          name: my-artifact
          path: output/main.pdf

      - name: Getdate and time from README.md
        id: get_datetime
        uses: actions/github-script@v5
        with:
          script: |
            const fs = require('fs');

            // Read the README.md file
            const data = fs.readFileSync('README.md', 'utf8');
          
            // Regular expression to match the "Last updated" line
            const regex = /Last updated: (\d{4}-\d{2}-\d{2}--\d{2}-\d{2}-\d{2})/;
          
            // Find the match
            const match = data.match(regex);
          
            if (match) {
                // Extract the date and time from the match
                const dateTime = match[1];
                console.log(`Date and Time: ${dateTime}`);
                return dateTime;
            } else {
                console.log('No "Last updated" line found.');
                return match;
            }

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        with:
          tag_name: Release-${{ steps.get_datetime.outputs.result }}
          release_name: Release ${{ steps.get_datetime.outputs.result }}
          draft: false
          prerelease: false
         
      - uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: output/main.pdf
          asset_name: ${{ steps.get_datetime.outputs.result }}main.pdf #
          asset_content_type: application/pdf