name: Test Upload

on:
  push:
    branches: 
      - main

jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: mkdir -p output
      - run: ls -a
      - run: touch output/world.txt
      - run: echo "hello" > output/world.txt
      - run: cat main.tex > output/world.txt
      - uses: actions/upload-artifact@v4
        with:
          name: my-artifact
          path: output/world.txt
      - name: Get current date and time
        id: get_date
        uses: actions/github-script@v5
        with:
          script: |
            const timeZone = 'Asia/Yekaterinburg'; // Specify your desired time zone here
            const date = new Date();
            const formatter = new Intl.DateTimeFormat('en-US', {
              timeZone: timeZone,
              year: 'numeric',
              month: '2-digit',
              day: '2-digit',
              hour: '2-digit',
              minute: '2-digit',
              second: '2-digit'
            });
            const formattedDate = formatter.format(date).replace(/[:\-]/g, ' ').replace(' ', '--');
            return formattedDate;
         
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        with:
          tag_name: ${{ steps.get_date.outputs.result }}
          release_name: Release ${{ steps.get_date.outputs.result }}
          draft: false
          prerelease: false
      - uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: output/world.txt
          asset_name: -${{ steps.get_date.outputs.result }}-world.txt
          asset_content_type: application/txt