name: Test Upload

on:
  push:
    branches: 
      - main
      - dev
    tags:
       - '*'
  pull_request:
    branches: [ master ]

jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - run: mkdir -p output
      - run: touch output/world.txt
      - run: echo hello > output/world.txt
      - run: cat main.tex > output/world.txt
      - uses: actions/upload-artifact@v4
        with:
          name: my-artifact
          path: path/to/artifact/world.txt
