name: Test Upload

on:
  push:
    branches: 
      - main

jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up TeX Live
        uses: xu-cheng/texlive-action@v2
        with:
          scheme: full
          run: | 
            lualatex -shell-escape -interaction=nonstopmode -file-line-error "main".tex
            lualatex -shell-escape -interaction=nonstopmode -file-line-error "main".tex
            lualatex -shell-escape -interaction=nonstopmode -file-line-error "main".tex

      - name: Upload PDF as artifact
        uses: actions/upload-artifact@v4
        with:
          name: output_pdf
          path: main.pdf

      - name: Getdate and time from README.md
        id: get_datetime
        uses: actions/github-script@v5
        with:
          script: |
            const fs = require('fs');

            // Read the README.md file
            const data = fs.readFileSync('README.md', 'utf8');
          
            // Regular expression to match the "Last updated" line
            const regex = /Last updated: (\d{4}-\d{2}-\d{2}--\d{2}-\d{2}-\d{2})/;
          
            // Find the match
            const match = data.match(regex);
          
            if (match) {
                // Extract the date and time from the match
                const dateTime = match[1];
                console.log(`Date and Time: ${dateTime}`);
                return dateTime;
            } else {
                console.log('No "Last updated" line found.');
                return match;
            }
           
      - name: Generate asset name
        id: generate_asset_name
        run: echo "::set-output name=asset_name::${{ steps.get_datetime.outputs.result }}_main.pdf"
      
      - run: echo "${{ steps.generate_asset_name.outputs.asset_name }}"

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        with:
          tag_name: Release-${{ steps.get_datetime.outputs.result }}
          release_name: Release ${{ steps.get_datetime.outputs.result }}
          draft: false
          prerelease: false
         
      - uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: main.pdf
          asset_name: ${{ steps.generate_asset_name.outputs.asset_name }}
          asset_content_type: application/pdf