name: Test Upload

on:
  push:
    branches: 
      - main
      - dev
    tags:
       - '*'
  pull_request:
    branches: [ master ]

jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: mkdir -p output
      - run: ls -a
      - run: touch output/world.txt
      - run: echo "hello" > output/world.txt
      - run: cat main.tex > output/world.txt
      - uses: actions/upload-artifact@v4
        with:
          name: my-artifact
          path: output/world.txt
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        with:
          tag_name: ${{ github.ref_name }}
          release_name: Release ${{ github.ref_name }}
          draft: false
          prerelease: false
      - uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: output/world.txt
          asset_name: world.txt
          asset_content_type: application/txt
          
name: "Download Button Action"

on:
  release:
  types:
    - published
  workflow_dispatch:
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Get latest release
      id: get-latest-release
      uses: InsonusK/get-latest-release@v1.0.1
      with:
        myToken: ${{ github.token }}
        view_top: 1
    - name: Readme Download Button Action
      env:
        GITHUB_USER: "i-v-a-n-h-o-e"
        REPO: "LatexTest"
        FORMAT: "txt"
        VERSION: "${{ steps.get-latest-release.outputs.tag_name }}"
        COLOR: "blue"
        BEGIN_TAG: "<!-- BEGIN LATEST DOWNLOAD BUTTON -->"
        END_TAG: "<!-- END LATEST DOWNLOAD BUTTON -->"
        run: |
            UPDATE=$(cat README.md | perl -0777 -pe 's#(${{ env.BEGIN_TAG }})(?:.|\n)*?(${{ env.END_TAG }})#${1}\n[![Download ${{ env.FORMAT }}](https://custom-icon-badges.herokuapp.com/badge/-Download-${{ env.COLOR }}?style=for-the-badge&logo=download&logoColor=white "Download ${{ env.FORMAT }}")](https://github.com/${{ env.GITHUB_USER }}/${{ env.REPO }}/archive/${{ env.VERSION }}.${{ env.FORMAT }})\n${2}#g')
            echo "${UPDATE}" > README.md
    - uses: EndBug/add-and-commit@v7
      with:
        message: "docs(readme): Bump download button version to ${{ steps.get-latest-release.outputs.tag_name }}"
        default_author: github_actions
        branch: main