name: LaTex Compile&Upload

on:
  push:
    branches: 
      - main

jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: LaTex Compile
        uses: xu-cheng/texlive-action@v2
        with:
          scheme: full
          run: | 
            lualatex -shell-escape -interaction=nonstopmode -file-line-error "main".tex
            lualatex -shell-escape -interaction=nonstopmode -file-line-error "main".tex
            lualatex -shell-escape -interaction=nonstopmode -file-line-error "main".tex

      - name: Upload PDF as artifact
        uses: actions/upload-artifact@v4
        with:
          name: output_pdf
          path: main.pdf
    
  prepare_release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          sparse-checkout: |
            README.md
          sparse-checkout-cone-mode: false

      - name: Getdate and time from README.md
        id: get_datetime
        uses: actions/github-script@v7
        with:
          script: |
            const fs = require('fs');

            // Read the README.md file
            const data = fs.readFileSync('README.md', 'utf8');
          
            // Regular expression to match the "Last updated" line
            const regex = /Last updated: (\d{4}-\d{2}-\d{2}--\d{2}-\d{2}-\d{2})/;
          
            // Find the match
            const match = data.match(regex);
          
            if (match) {
                // Extract the date and time from the match
                const dateTime = match[1];
                console.log(`Date and Time: ${dateTime}`);
                return dateTime;
            } else {
                console.log('No "Last updated" line found.');
                return match;
            }
           
      - name: Set output
        id: set_output
        run: |
          echo "::set-output name=date_time::${{ steps.get_datetime.outputs.result }}"
          echo "::set-output name=file_name::${{ steps.get_datetime.outputs.result }}_main.pdf"
    outputs:
      date_time: ${{ steps.set_output.outputs.date_time }}
      file_name: ${{ steps.set_output.outputs.file_name }}

  create_and_upload_release:
    needs: [build_latex, prepare_release]
    runs-on: ubuntu-latest
    steps:
      - name: Check outputs
        id: check_outputs
        run: |
          echo "${{ needs.prepare_release.outputs.date_time }}"
          echo "${{ needs.prepare_release.outputs.file_name }}"
      - name: Download PDF artifact
        uses: actions/download-artifact@v4
        with:
            name: output_pdf

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        with:
          tag_name: Release-${{ needs.prepare_release.outputs.date_time }}
          release_name: Release ${{ needs.prepare_release.outputs.date_time }}
          draft: false
          prerelease: false
         
      - uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./main.pdf
          asset_name: ${{ needs.prepare_release.outputs.file_name }}
          asset_content_type: application/pdf
  

  # test_checkout:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v4
  #     - run: |
  #           date > generated.txt
  #           git config user.name github-actions
  #           git config user.email github-actions@github.com
  #           git add .
  #           git commit -m "generated"
  #           git push