name: Test Upload

on:
  push:
    branches: 
      - main
      - dev
    tags:
       - '*'
  pull_request:
    branches: [ master ]

jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: mkdir -p output
      - run: ls -a
      - run: touch output/world.txt
      - run: echo "hello" > output/world.txt
      - run: cat main.tex > output/world.txt
      - uses: actions/upload-artifact@v4
        with:
          name: my-artifact
          path: output/world.txt
      - uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false
      - uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: output/world.txt
          asset_name: world.txt
          asset_content_type: application/txt
